sudo: required
services:
    - docker

before_install:
    - docker build -t clayton76/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run clayton76/react-test npm test -- --coverage

after_success:
    - docker build -t clayton76/multi-client ./client
    - docker build -t clayton76/multi-nginx ./nginx
    - docker build -t clayton76/multi-server ./server
    - docker build -t clayton76/multi-worker ./worker
    # Log in to the docker CLI (put docker credentials in Travis project...)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push clayton76/multi-client
    - docker push clayton76/multi-nginx
    - docker push clayton76/multi-server
    - docker push clayton76/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-245143831229
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY 
